// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrPYrCL9Sz5xhIVuv3mSLfBAteML4tifs',
    appId: '1:510321218410:web:94b293c5e488c5180ccb13',
    messagingSenderId: '510321218410',
    projectId: 'registrationpage-cf5d7',
    authDomain: 'registrationpage-cf5d7.firebaseapp.com',
    databaseURL: 'https://registrationpage-cf5d7-default-rtdb.firebaseio.com',
    storageBucket: 'registrationpage-cf5d7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzwtafQEwsd8Me9Nhxv0zndKUENbK0B1c',
    appId: '1:510321218410:android:c8e72a73c13cdf1d0ccb13',
    messagingSenderId: '510321218410',
    projectId: 'registrationpage-cf5d7',
    databaseURL: 'https://registrationpage-cf5d7-default-rtdb.firebaseio.com',
    storageBucket: 'registrationpage-cf5d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4PZAhgGb561ZSQ4rCYgFPBopvDC3ZYmM',
    appId: '1:510321218410:ios:27014b914658986d0ccb13',
    messagingSenderId: '510321218410',
    projectId: 'registrationpage-cf5d7',
    databaseURL: 'https://registrationpage-cf5d7-default-rtdb.firebaseio.com',
    storageBucket: 'registrationpage-cf5d7.firebasestorage.app',
    iosBundleId: 'com.example.registrationPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4PZAhgGb561ZSQ4rCYgFPBopvDC3ZYmM',
    appId: '1:510321218410:ios:27014b914658986d0ccb13',
    messagingSenderId: '510321218410',
    projectId: 'registrationpage-cf5d7',
    databaseURL: 'https://registrationpage-cf5d7-default-rtdb.firebaseio.com',
    storageBucket: 'registrationpage-cf5d7.firebasestorage.app',
    iosBundleId: 'com.example.registrationPage',
  );

}